# Generated by Django 4.2 on 2025-04-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('treatments', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='disease_images/')),
            ],
        ),
    ]
