# Generated by Django 4.2 on 2025-04-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='diseases',
            field=models.CharField(blank=True, choices=[('diabetes', 'Diabetes'), ('cancer', 'Cancer'), ('asthma', 'Asthma'), ('heart', 'Heart Disease'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
