# Generated by Django 4.2 on 2025-04-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_user', '0002_user_birthdate_user_country_user_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diseases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
