# Generated by Django 4.2 on 2025-04-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('holy_book', models.CharField(max_length=255)),
                ('verse', models.CharField(max_length=255)),
            ],
        ),
    ]
